#!/usr/bin/env bash
# Install or update API Client for the current user (Linux).
#
#   ./install.sh              install, or update to the latest version
#   ./install.sh --uninstall  remove the launcher (the repository is left untouched)
#
# Nothing is written outside your home folder and sudo is never used.
set -euo pipefail

APP_ID="api-client"
APP_NAME="API Client"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="$REPO_DIR/.venv"
BIN_DIR="$HOME/.local/bin"
DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
DESKTOP_FILE="$DATA_HOME/applications/$APP_ID.desktop"
ICON_FILE="$DATA_HOME/icons/hicolor/scalable/apps/$APP_ID.svg"
LAUNCHER="$BIN_DIR/$APP_ID"

info()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
ok()    { printf '\033[1;32m✓\033[0m %s\n' "$*"; }
warn()  { printf '\033[1;33m!\033[0m %s\n' "$*"; }
fail()  { printf '\033[1;31m✗\033[0m %s\n' "$*" >&2; exit 1; }

refresh_desktop_caches() {
    command -v update-desktop-database >/dev/null && update-desktop-database -q "$DATA_HOME/applications" || true
    command -v gtk-update-icon-cache >/dev/null && gtk-update-icon-cache -q -t "$DATA_HOME/icons/hicolor" || true
}

uninstall() {
    info "Removing $APP_NAME launcher"
    rm -f "$LAUNCHER" "$DESKTOP_FILE" "$ICON_FILE"
    refresh_desktop_caches
    ok "Launcher removed. Your projects, settings ($DATA_HOME/$APP_ID) and this repository were kept."
    exit 0
}

[[ "${1:-}" == "--uninstall" ]] && uninstall
[[ "$(uname -s)" == "Linux" ]] || fail "This script is for Linux. See README.md for Windows/macOS."

# 1. Update the code -----------------------------------------------------------
if git -C "$REPO_DIR" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    info "Updating repository (git pull)"
    if [[ -n "$(git -C "$REPO_DIR" status --porcelain --untracked-files=no)" ]]; then
        warn "You have local changes; skipping git pull so they are not lost."
    elif ! git -C "$REPO_DIR" pull --ff-only; then
        warn "git pull failed (offline or diverged history). Continuing with the current version."
    fi
else
    warn "Not a git clone; skipping update."
fi

# 2. Python --------------------------------------------------------------------
PYTHON=""
for candidate in python3.14 python3.13 python3.12 python3; do
    if command -v "$candidate" >/dev/null && \
       "$candidate" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 12) else 1)' 2>/dev/null; then
        PYTHON="$(command -v "$candidate")"
        break
    fi
done
[[ -n "$PYTHON" ]] || fail "Python 3.12 or newer is required (e.g. 'sudo dnf install python3')."
ok "Using $("$PYTHON" --version) at $PYTHON"

# 3. Virtual environment and dependencies -------------------------------------
if [[ -x "$VENV_DIR/bin/python" ]] && ! "$VENV_DIR/bin/python" -c 'import sys' 2>/dev/null; then
    warn "Existing virtual environment is broken; recreating it."
    rm -rf "$VENV_DIR"
fi
if [[ ! -x "$VENV_DIR/bin/python" ]]; then
    info "Creating virtual environment"
    "$PYTHON" -m venv "$VENV_DIR" || fail "Could not create the venv (on Debian/Ubuntu: sudo apt install python3-venv)."
fi
info "Installing dependencies"
"$VENV_DIR/bin/python" -m pip install --quiet --upgrade pip
"$VENV_DIR/bin/python" -m pip install --quiet --upgrade -r "$REPO_DIR/requirements.txt"
"$VENV_DIR/bin/python" -c 'import PySide6, httpx' || fail "Dependencies did not install correctly."
ok "Dependencies ready"

# 4. Launcher: command, icon and menu entry -----------------------------------
info "Installing launcher"
mkdir -p "$BIN_DIR" "$(dirname "$DESKTOP_FILE")" "$(dirname "$ICON_FILE")"

cat > "$LAUNCHER" <<LAUNCH
#!/usr/bin/env bash
# Generated by $REPO_DIR/install.sh — re-run that script to update.
cd "$REPO_DIR" && exec "$VENV_DIR/bin/python" "$REPO_DIR/main.py" "\$@"
LAUNCH
chmod +x "$LAUNCHER"

cp "$REPO_DIR/assets/$APP_ID.svg" "$ICON_FILE"

cat > "$DESKTOP_FILE" <<DESKTOP
[Desktop Entry]
Type=Application
Name=$APP_NAME
GenericName=REST Client
Comment=Lightweight REST client for backend developers
Exec=$LAUNCHER %f
Icon=$APP_ID
Terminal=false
Categories=Development;WebDevelopment;
Keywords=api;rest;http;postman;spring;
StartupWMClass=$APP_ID
StartupNotify=true
DESKTOP
chmod +x "$DESKTOP_FILE"
refresh_desktop_caches
ok "Menu entry: $DESKTOP_FILE"
ok "Command:    $LAUNCHER"

case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) warn "$BIN_DIR is not in your PATH; the menu entry works, but add it to run '$APP_ID' from a terminal." ;;
esac

echo
ok "$APP_NAME installed. Open it from your applications menu or run: $APP_ID [backend-folder]"
echo "   To update later, run ./install.sh again."
